### ISSUE TITLE
The * operator should perform dot product of vectors

### ISSUE THREAD

**Issue by lucianferoiu** [libktx/ktx#101]
Using the operator `*` to perform element-wise multiplication (e.g. for `Vector2` in #ktx-math) is a sin. There is a special circle in Hell (of length 3π) for those that blaspheme about Linear Algebra.

I propose instead an `infix fun` named _hadamard_ or _schur_ -- as penance for those who seek brevity at the cost of their souls.

**Comment by czyzby** [comment]
Um.

Not that you're wrong, but this is pretty much the behavior that _I_ would expect as a simple ignorant app developer, who normally doesn't do a lot of math. I mean, in case of simple mobile games, you're far more likely to want to combine something like vector representing speed with sort of a speed bonus vector with simple multiplication, rather than perform any advanced calculations, right? This might take me straight to hell, but I'm guessing I'd write such extension in personal projects sooner or later even if it was removed from there.

If you want to "fix" this issue, I'd be happy to go through the pull request though.

**Comment by lucianferoiu** [comment]
Yeah, I know, it was mostly tongue-in-cheek. I understand the context. And it mainly stems from the fact of using _vector_ when we actually mean a tuple of numbers and we just want to streamline a set of operations to the whole tuple...

As a serious proposition now: maybe we should use `*=` (i.e. `timesAssign(..)`) for the Hadamard product, since as you say, it's **mostly** used as a self-updating  `position *= velocity`, and reserve the regular multiplication for dot products, since the result is not something self-updating but rather a new kind of object (a scalar or a square matrix -- if we add the notion of a _transpose_ to the mix).
But only if enough people agree with this - otherwise indeed, practicality wins the day, sinners be damned...

**Comment by czyzby** [comment]
`times` operator lets you use `*=` for free. Providing two different implementations for what's supposed to be the same operator might be really confusing, especially if you want to chain some operations on vectors. I'm glad you agree with the practical approach. If more people want the `dot` instead of `scl`, changing the implementation would be trivial - but for now let's just leave it in the backlog.

**Comment by lucianferoiu** [comment]
Alrighty :)

Cheers!

**Comment by czyzby** [comment]
Dot product was added as `dot` infix function in #130.
