### ISSUE TITLE
[discussion] notes on input processing and Stage

### ISSUE THREAD

**Issue by keturn** [libktx/ktx#164]
Notes on stumbling blocks I (as someone trying to learn this library from Kotlin, without prior exposure to libgdx in Java) ran in to when trying to add input handling:

The interface I've seen talking about event listeners is [`ktx-actors`](https://github.com/libktx/ktx/tree/master/actors), and I think I will want to be using scene2d anyway, so okay, I'll make a `KtxInputListener`.

except just _creating_ a listener doesn't do anything, something has to route input to it. I need to pass it to an `addListener`. What has `addListener`? a `Stage` does.

How do I create a `Stage`? The `ktx-actors` and `ktx-scene2d` pages talk a lot about Actors, which seem to need a Stage, but never actually show setting up a Stage or adding Actors to one.

What's the relationship between a Stage and a Screen? Seems like each Screen would want its own Stage. Doesn't sound like it would make sense to have a Stage persist beyond a Screen.

I don't see any existing relationship, so I'll just put `val stage = Stage()` in my `KtxScreen` subclass.

Okay, now I have a Stage, added a listener to it, and ... that doesn't do anything.

Of course, the Stage has to be integrated into the mainloop somehow, so I'll add `stage.act(); stage.draw()` to my screen's `render`, and ... the listeners still don't fire.

I guess `stage.act()` isn't enough for the stage to get events, so, uh, [fumbles around until I find [this GDX example](https://github.com/julienvillegas/libgdx.info-inputMultiplexing/blob/master/core/src/com/mygdx/game/Screens/TitleScreen.java)], there's a `Gdx.input.inputProcessor` that I set to my Stage. Somewhere. The example has it in `screen.show` so I'll do that.

Okay! I seem to have input events now!

But I am left with lingering doubts about if there's anything else about the connections between Stage and Screen and Gdx.input that I'm supposed to be managing somewhere.

**Comment by czyzby** [comment]
[This is a good LibGDX article about Scene2D basics.](https://github.com/libgdx/libgdx/wiki/Scene2d)

* `InputProcessors` handle raw input from the users. If you want to add custom handling to each input type, you can implement this interface from scratch and catch raw events. Note that you should register them with `Gdx.input` - preferably once, before expected usage.
* `Screen` is out there for convenience. Most applications have more than a single view, so in order to split their code logically, you can define a separate `Screen` for each view. Note that you don't have to use `Screens` at all and instead you can define view transitions on your own. It's not a core part of LibGDX like the `InputProcessors` are.
* `Stage` is a root actor container. You can draw actors manually if you're really brave, but `Stage` is out there to do that for you. It also handles viewports, events, actions, animations and probably a ton of other stuff that I forgot to mention. If also happens to implement `InputProcessor`, so it can notify the event listeners that you attach to your actors.

As far as instances count goes, there are a few approaches. You can define a separate `Stage` for each view, but you can also use a single stage and switch actors upon changing views. So basically, every view would just define a list of actors (or just a root actor) and when changing the view, you would remove all current actors and add the actors from the next one. You can pair that with some fading animations for cool screen transition effects.

Anyway, even if you define multiple `Stages`, they should reuse `Batch` that they use to draw the actors.

Hope it clears that up.

---

I'll add an example of creating a `Stage` to `ktx-scene2d`, thanks.

**Comment by czyzby** [comment]
I added a `Stage` section to `ktx-scene2D` README, as well as `stage` factory method to `ktx-actors`. Thanks.
