### ISSUE TITLE
Dialog builder absent in ktx-vis module

### ISSUE THREAD

**Issue by Divelix** [libktx/ktx#219]
I noticed that there is inline function for `window`, but no function for `dialog` in `builder.kt` file. And also there is no extension function for `dialog' in ktx-style.

**Comment by czyzby** [comment]
We decided [not to include dialogs](https://github.com/libktx/ktx/issues/5#issuecomment-234370420) in VisUI extensions, since they would have some name collisions with KTX widget builders, they are easy to reproduce with much more customizable windows, and I think @kotcrab was going to remove them either way. Feel free to propose a PR if you'd like to see dialogs in `ktx-vis`, but we're not planning to add them for now.

In contrary to `ktx-vis`, `ktx-scene2d` does provide support for constructing dialogs.

There is no `dialog` style, since dialogs use `window` styles instead. You'll notice that LibGDX `Dialog` implementation extends `Window` and accepts `WindowStyle` in its constructor. If you want to customize your dialogs, use `window` extension.
