### ISSUE TITLE
Lack of documentation on `vis-style` module

### ISSUE THREAD

**Issue by Divelix** [libktx/ktx#225]
It would be nice to add example to wiki of how to specify values for all VisUI specific widgets using default @kotcrab skin, beacuse it is really hard to blinly figure out how to setup your first skin using ktx.

For instance, I was trying to make `TabbedPane` by following ktx wiki, but there is no info on how to load skin parameters for that widget. So, I started to insert arbitrary values from skin until I stopped getting compile errors. There is my code, that compiles well, but tabbed pane itself looks aweful as I used arbitrary values for drawables.

```kotlin
val uiSkin = skin(manager.get(Constants.UISKIN_ATLAS)) {
    val btn = visTextButton {
        up = it["button"]
        font = manager.get<BitmapFont>(Constants.ROBOTO_ALIAS_DEFAULT)
    }
    tabbedPane("vertical") {
        background = it["window-border-bg"]
        separatorBar = it["separator"]
        buttonStyle = btn
        draggable = false
        vertical = true
    }
    visImageButton {
        up = it["button"]
        down = it["button-down"]
    }
    visImageButton("close-active-tab", extend = defaultStyle)
    visImageButton("close", extend = defaultStyle)
}
VisUI.load(uiSkin)
```
Why "close-active-tab"? Why "close"? Why it asks for image button style? How could I know that?

So, I ask you to just add sample code [here maybe](https://github.com/libktx/ktx/tree/master/vis-style) on how to setup values for default VisUI skin atlas to let users understand how it works, may be with some comments (would be nice).

**Comment by czyzby** [comment]
`ktx-style` and `ktx-vis-style` are just syntax sugar for filling existing styles from Scene2D and VisUI respectively. One of the reasons why these modules are a bit light on documentation is because they don't introduce any drastically new APIs, just a different way to define skins programmatically.

So, for example, when you're calling `visTextButton`, you're getting an instance of `com.kotcrab.vis.ui.widget.VisTextButton.VisTextButtonStyle` and working directly on its fields. There are no `ktx-style` wrappers of the styles, you're working directly with VisUI.

`close-active-tab` happens to be one of the styles available in the original `JSON` file with the style definition. You can find all defined styles [here](https://github.com/kotcrab/vis-ui/tree/master/ui/src/main/resources/com/kotcrab/vis/ui/skin/x1).

Still, lack of better documentation is a valid point. We'll try to improve README files of these modules.

**Comment by czyzby** [comment]
By the way @Divelix, all of the KTX extensions work on existing skins, so you can load official `Skin` instance from VisUI and add/modify only your own custom styles, while relying on the defaults for the rest.

```kotlin
VisUI.load()
val skin = VisUI.getSkin()
skin.visTextButton {
  // Define your style here.
}
```

**Comment by Divelix** [comment]
Didn't know about that default thing, thank you. I think that should be on `vis-style` wiki.

**Comment by czyzby** [comment]
@Divelix I've extended `ktx-style` and `ktx-vis-style` documentation. `ktx-vis-style` still encourages user to go through the `ktx-style` documentation for details, but now it includes a VisUI-specific example of loading and extending the default VisUI `Skin`.

**Comment by czyzby** [comment]
If you think the documentation still lacks some particular examples, please reopen the issue.
