### ISSUE TITLE
gdxListOf gone?

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#280]
After refreshing to latest SNAPSHOT today I saw that gdxListOf is no longer there. Also tried version b6 but also there it is gone., Seems like I can simply replace it with gdxArrayOf but I wonder what happened to gdxListOf? Was that something very old that was cached somehow on my end?

![image](https://user-images.githubusercontent.com/93260/80301238-382b4400-87a3-11ea-8eec-fd1944cb6752.png)

**Comment by czyzby** [comment]
No, it was removed in the `1.9.10-b6` release. It was a very old collection with some safety issues that would require significant changes.

I reviewed the implementation while refactoring operators in `gdx-collections` and noticed that `PooledList` reuses a single iterator, which makes concurrent iteration impossible and might lead to some unexpected behaviours. Besides, the name suggests that it is a direct equivalent to stdlib `listOf`, while this is not the case - this was more of a linked list and `gdxArrayOf` should be preferred most of the time.

What were you using it for? If that was a collection you iterated over and removed elements during iteration, `PooledLinkedList` from LibGDX would be a direct equivalent with a slightly worse API (it's not `Iterable`). Otherwise you can use `gdxArrayOf` or linked list from stdlib.

If you'd like to refactor the collection (e.g. add pooled iterator instances rather than a single reused iterator), I'll happily review the PR, but I have no plans to add it for now.

**Comment by Quillraven** [comment]
I could replace it with gdxArrayOf. I think it originally came from your example with assetstorage where we stored the loadAsync calls in a flat list to use joinAll later.

Changing to gdxArrayOf worked here as well and it also contained the flatten function.

I will close this issue then - solved  :)

**Comment by czyzby** [comment]
That's exactly what I've mentioned - you used `gdxListOf` instead of `listOf`, while what you needed was an `ArrayList` equivalent - `gdxArrayOf`. `PooledList` (or `gdxListOf`) was a pretty niche collection with too vague of a name, and admittedly it was not a very well designed part of KTX API.
