### ISSUE TITLE
Problem with Container builder

### ISSUE THREAD

**Issue by Divelix** [libktx/ktx#297]
I keep fixing my UI code after upgrade to `b6` and found out that `container()` builder doesn't work anymore. I have some class
```kotlin
class MyGroup(content: MyContent): Group() {...}
```
And previously I used it as cells in table this way:
```kotlin
table {
    someArrayOfContent.forEach {
        container(MyGroup(it)) // this line doesn't work anymore
    }
}
```
I tried to do the following, which fixes compile error, but doesn't draw anything in UI:
```kotlin
container { MyGroup(it) }
container { actor = MyGroup(it) }
```
What am I doing wrong?

**Comment by czyzby** [comment]
Passing an actor to the `container` method would require you to build the actor in the first place. The KTX approach is to build everything with the DSL, so to answer your question, this is the expected API usage:

```kotlin
container {
   label("This is a container with a label!")
}
```

However, since in your case you do have a custom actor that you build manually, you can use container API directly:

```kotlin
container {
  addActor(MyGroup(it))
}
```

That should do it. In fact, `container { actor = MyGroup(it) }` should work as well.

After this issue, I'm considering adding that utility back though.

**Comment by czyzby** [comment]
Right, I just remembered that you used `ktx-vis` before. Now that I think about it, `container(Actor)` method was never a part of `ktx-scene2d` API - `ktx-vis` had it, but it was removed during the rewrite. I might move the previous `ktx-vis` implementation to `ktx-scene2d`.

**Comment by czyzby** [comment]
Your first code snippet should now work in KTX `1.9.11-SNAPSHOT`.

**Comment by Divelix** [comment]
Do you plan to return it only to `ktx-vis` or `ktx-scene2d` too? Because it is actually really useful thing to have non-widget actor in UI and `Container` builder is a pretty nice crutch to use non-widget `Actor` in fancy ktx DSL.

In my case I used `Group` as superclass instead of `Table` because it lets me make element of fixed size with absolute positioning of inner elements (because I need "blocks" that always have the same look independent from device aspect ratio and parent table configuration).

**Comment by czyzby** [comment]
Both. I added it to `ktx-scene2d`, and `ktx-vis` now ends this module, so it will be available in both.
