### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by DuchGhast** [libktx/ktx#308]

**Comment by czyzby** [comment]
No, it is not, @DuchGhast. I actively tend to all of the issues and PRs. The latest contributions can be seen on the [`develop`](https://github.com/libktx/ktx/tree/develop) branch and accessed as a snapshot release, which is currently `1.9.11-SNAPSHOT`. It's just that all of the major features that I wanted to add are complete and I don't actively develop new KTX modules nowadays. All contributions are still welcome.

I might go through all of the open issues and PRs this month and close some of these, especially the `ktx-tools` contribution.

**Comment by keturn** [comment]
As someone who has been lurking on the github notifications, I confirm czyzby's assessment. It's not super active, I think mostly because gamedev in Kotlin is still a pretty small niche, but czyzby does an admirable job of keeping things up-to-date and responding to the occasional contributions that drop by now and then.

I was more worried more about libgdx itself, but they got a new release out a couple months ago!

(The thing I've been tinkering with lately is based on LWJGL. It really doesn't need libgdx's variety of backends, so it won't be switching to something libgdx-based, but I halfway wish it would just because I think libktx has done such a fine job of figuring out what Kotlin interfaces should look like. When I eventually get around to doing more Kotlin work in that project, I may look to libktx for inspiration to see if we need a similar layer over LWJGL.)
