### ISSUE TITLE
Binding a KtxGame instance as a singleton with ktx-inject results in a stack overflow error when Context#dispose() is called

### ISSUE THREAD

**Issue by steven-peralta** [libktx/ktx#309]
Previously, KtxGame extended KotlinApplication which didn't implement the Disposable interface, so when you binded it with ktx-inject this bit of code was skipped over in SingletonProvider:

```Kotlin
  override fun dispose() {
    (singleton as? Disposable)?.dispose()
  }
```

Now, when you add a KtxGame instance as a singleton, this results in a recursive call to the `dispose()` method that would call `Context#dispose()`. Here is an example:

```Kotlin
class Game : KtxGame<KtxScreen>() {
    private val ctx = Context()

    override fun create() {
        ctx.register {
            bindSingleton(this@Game)
        }
    }

    override fun dispose() {
        ctx.dispose()
    }
}
```

Here are the errors:
```
Caused by: java.lang.StackOverflowError
	at ktx.inject.Context.dispose(inject.kt:197)
	at com.k9rosie.rpggame.Game.dispose(Game.kt:28)
	at ktx.inject.SingletonProvider.dispose(inject.kt:234)
	at ktx.inject.Context.dispose(inject.kt:200)
	at com.k9rosie.rpggame.Game.dispose(Game.kt:28)
	at ktx.inject.SingletonProvider.dispose(inject.kt:234)
	at ktx.inject.Context.dispose(inject.kt:200)
	at com.k9rosie.rpggame.Game.dispose(Game.kt:28)
	at ktx.inject.SingletonProvider.dispose(inject.kt:234)
        ... and so on
```

**Comment by steven-peralta** [comment]
I can confirm that this doesn't happen with ktx version >= 1.9.10-b6

**Comment by czyzby** [comment]
This is expected behavior in a way. You're essentially asking the `Context` to dispose of all of its components, one of which is `KtxGame`.

`KtxGame` is (and was) always disposable with its `dispose` method, but it just wasn't implementing the universal interface for it, and lacked all of the utilities for disposable objects. You could argue that before #288 the lack of `Disposable` in classes like `KtxScreen` was causing bugs, as the screens weren't properly disposed by the context and other asset managers.

To avoid this exception, try removing your `Game` object from the `Context` first:

```kotlin
    override fun dispose() {
        ctx.remove<Game>()
        ctx.dispose()
    }
```

I could improve the `ktx-inject` documentation with an example how to avoid this bug.

**Comment by czyzby** [comment]
Just to expand on this, any other `Disposable` class that would add itself to and dispose a `Context` would throw the same exception. Say, if you decided to move the `Context` to another class in an older KTX version, you could experience the same kind of issue. I'd say in general binding the container class to the `Context` is tricky and requires some conscious lifecycle management.

**Comment by czyzby** [comment]
@steven-peralta I expanded the documentation. Let me know if this solves the issue for you.

**Comment by steven-peralta** [comment]
Thanks for expounding on this issue. Your comments were really helpful.
