### ISSUE TITLE
Lambda functions in ktx-vis do not always use KWidget subclass as receiver

### ISSUE THREAD

**Issue by Double-O-Seven** [libktx/ktx#354]
I wanted to use `visScrollPane` from `ktx-vis`, but I noticed that the `this`-receiver of the lambda is only of type `VisScrollPane` instead of `KVisScrollPane`, even though a `KVisScrollPane` is passed to the actor call. Why is that?
Because the receiver is not a `KWidget`, I cannot use nested DSL calls there.

Is there a specific reason for this or is this just an oversight?

`visScrollPane` is just an example for this, there are other such cases in `factory.kt`.

**Comment by czyzby** [comment]
Some widgets are not wrapped with `KWidget`, because they cannot have children - like `VisLabel`. In this case this is indeed an oversight. I'll go through the factories of `ktx-scene2d` and `ktx-vis` to make sure that the lambdas consume the correct types. Thanks.

**Comment by czyzby** [comment]
As far as I can tell, the `init` parameter was wrong only for `visScrollPane` and `visSplitPane`. There's also a similar problem with `tableInit` in `buttonBar`, but since we're not creating the table manually in this case, it is not a `KWidget` in the first place. The fix should be available shortly as a snapshot release (`1.9.14-SNAPSHOT`), and I'll probably do another stable release this week.

**Comment by czyzby** [comment]
The fix is now available in KTX `1.9.14-b2`.
