### ISSUE TITLE
Is this repo actively maintained?

### ISSUE THREAD

**Issue by Rhtyme** [libktx/ktx#444]
First of all, thanks a lot for this amazing library, it is very helpful. I am new to libgdx, but have solid experience in Kotlin. That is way I am planning to start libgdx in Kotlin through this library. 
However, I see that the last commit was more than 4 months ago (as of writing this issue), so I wonder if it is actively maintained (kinda LTS) so that we would not miss any new updates from libgdx as well (sorry if the question is not valid, I am new to this repo, and don't know much of the aspects).

**Comment by czyzby** [comment]
Hey @Rhtyme. First of all, latest features are on the [`develop`](https://github.com/libktx/ktx/tree/develop) branch. The main branch contains the latest stable release, so that the documentation is consistent with what you're getting when you set up your application through e.g. `gdx-liftoff`.

That being said, new features are not actively developed and are mostly contributed by KTX community. I usually try to merge smaller utilities pretty quick, but larger contributions like new modules can drag a little bit since I maintain the library in my spare time. As for newer libGDX versions, I try to update major dependencies pretty regularly. Basically, not much has changed since the last time it was asked in #308. ;)

**Comment by czyzby** [comment]
I've released the latest changes today, so you should see a bit more activity in the main branch. :)

**Comment by Rhtyme** [comment]
thanks for the quick response. Yes, I totally understand this is open source project, however I see that now the repo looks much fresh ;)
