### ISSUE TITLE
scene2d image without drawable

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#485]
Hi,

right now the `image` scene2d extension requires a non-null `Drawable`:

```kotlin
@Scene2dDsl
@OptIn(ExperimentalContracts::class)
inline fun <S> KWidget<S>.image(
  drawable: Drawable,
  init: (@Scene2dDsl Image).(S) -> Unit = {},
): Image {
  contract { callsInPlace(init, InvocationKind.EXACTLY_ONCE) }
  return actor(Image(drawable), init)
}
```

However, it is valid to pass "null" as a drawable and this can be useful if the real drawable is set later on but you still want to add the image to the table to have the correct layout.

Would it be okay to make it `Drawable?` instead of `Drawable`? This might be also true for other extensions with drawables but I did not check them all.

Or is there a different solution to it?

**Comment by czyzby** [comment]
If an image without a drawable can exist and might make sense for some use cases, it should be possible to create with the DSL. This might be an oversight, but it can be easily amended without breaking the API. `Drawable?` with a `null` default could be a way to solve this, I just have to check first if an image without a drawable isn't otherwise broken (e.g., thowing NPE on draw). Thanks for bringing this up.

**Comment by Quillraven** [comment]
Imo this should be just fine and at least in my case it works. Here is also the official documentation of `setDrawable` which mentions it may be null:

![image](https://github.com/libktx/ktx/assets/93260/604c9e16-17d7-492d-badf-2e9a3b66a5d6)

**Comment by Quillraven** [comment]
Will be fixed by the linked PR above
